apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Core platform services for the k3s cluster
  sourceRepos:
    - https://github.com/wekamlesh/project-snorlax.git
    - https://helm.nginx.com/stable
    - oci://quay.io/jetstack/charts
    - https://charts.external-secrets.io
    - https://vmware-tanzu.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
